### ISSUE TITLE
Exception raised by the Daisy.SaveAsDAISY.Conversion.ConversionParameters.usingMainDocument

### ISSUE THREAD

**Issue by NPavie** [daisy/word-save-as-daisy#24]
The following exception report was sent by a user
```
Object reference not set to an instance of an object.

at Daisy.SaveAsDAISY.Conversion.ConversionParameters.usingMainDocument(DocumentParameters mainDocument)
at Daisy.SaveAsDAISY.Conversion.ConversionParametersForm..ctor(DocumentParameters document, ConversionParameters conversion, ResourceManager labelsManager)
at Daisy.SaveAsDAISY.Forms.GraphicalConverter.requestUserParameters(DocumentParameters currentDocument)
at Daisy.SaveAsDAISY.Addins.Word2007.Connect.SaveAsDaisy(IRibbonControl control, ConversionParameters conversionIntegrationTestSettings)
```

Investigation is ongoing, as I was not able yet to reproduce the issue.

**Comment by NPavie** [comment]
Issue could not be reproduced, closing
