### ISSUE TITLE
Conversion of single docx to dtbook XML: task crashed

### ISSUE THREAD

**Issue by prashantverma2014** [daisy/word-save-as-daisy#36]
[Uploading 11.Arm.History.docx…]()
An exception was reported by the saveAsDaisy addin.
- Addin Version: 2.8.1.0
- Running Architecture: x64
- OS: Microsoft Windows 10.0.22631 
- User or system wide install: user

Conversion of single docx to dtbook XML: task crashed
- The 'strong' start tag on line 2 position 9463 does not match the end tag of 'p'. Line 2, position 9482.

Stacktrace:
```
   at Daisy.SaveAsDAISY.Conversion.Converter.Convert(DocumentParameters document, Boolean applyPostProcessing)
   at Daisy.SaveAsDAISY.Addins.Word2007.Connect.ApplyScript(Script pipelineScript, IConversionEventsHandler eventsHandler, ConversionParameters conversionIntegrationTestSettings)
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Daisy.SaveAsDAISY.Conversion.WordToDTBookXMLTransform.MergeDocumentInTarget(DocumentParameters documentToMerge, XmlDocument mergeTarget)
   at Daisy.SaveAsDAISY.Conversion.WordToDTBookXMLTransform.ConvertDocument(DocumentParameters document, ConversionParameters conversion, XmlDocument mergeTarget)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by NPavie** [comment]
Hi @prashantverma2014 

It seems the file was not uploaded with the issue.
Can you send me back the file directly through email ?

Best regards

**Comment by prashantverma2014** [comment]
PFA

**Comment by prashantverma2014** [comment]
PFA

**Comment by NPavie** [comment]
@prashantverma2014 replying to the issue by mail with the attachment also seems to delete the attachment.
(Its possible that github prevent docx file for security reasons)

Can you send it to directly by email at pavie.nicolas@gmail.com ?

**Comment by NPavie** [comment]
After analysis, the issue seemed to be related to #35
(the error occurs near a pagenum insertions)

To be confirmed with the latest test installer, but it should be fixed by ed8173cc99ad6f27433b2b617ca06b8e04ddea3f
