### ISSUE TITLE
Conversion of single docx to dtbook XML: task crashed

### ISSUE THREAD

**Issue by jptjoe** [daisy/word-save-as-daisy#49]
An exception was reported by the saveAsDaisy addin.
- Addin Version: 2.8.6.0
- Running Architecture: x64
- OS: Microsoft Windows 10.0.22631 
- User or system wide install: user
- Addin settings:
```xml
<Settings><PageNumbers  value="Custom" /><CharacterStyles value="False" /><ImageSizes value="original" samplingvalue="96" /><Footnotes level="0" position="inline" numbering="none" startValue="1" numberPrefix="" numberSuffix="" /><TTSConfig file="" /></Settings>
```
Conversion of single docx to dtbook XML: task crashed
- One or more errors occurred.
- An error occured during the XSL-based conversion
- An error occurred during a call to extension function 'FootNoteId'. See InnerException for a complete description of the error.
- Input string was not in a correct format.

Stacktrace:
```
   at Daisy.SaveAsDAISY.Conversion.Converter.Convert(DocumentParameters document, Boolean applyPostProcessing)
   at Daisy.SaveAsDAISY.Addins.Word2007.Connect.ApplyScript(Script pipelineScript, IConversionEventsHandler eventsHandler, ConversionParameters conversionIntegrationTestSettings)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Daisy.SaveAsDAISY.Conversion.Converter.Convert(DocumentParameters document, Boolean applyPostProcessing)
   at Daisy.SaveAsDAISY.Conversion.Converter.<>c__DisplayClass37_0.<Convert>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Xml.Xsl.Runtime.XmlExtensionFunction.Invoke(Object extObj, Object[] args)
   at System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction(String name, String namespaceUri, IList`1[] args)
   at <xsl:template name="InsertFootnotes">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, IList`1 level, IList`1 verfoot, IList`1 characterStyle, String sOperators, IList`1 sMinuses, String sNumbers, IList`1 sZeros)
   at <xsl:template name="compiler:generated"> (31)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current, XPathNavigator quote, IList`1 charparahandlerStyle, IList`1 dpiPara, IList`1 imgOptionPara, IList`1 mastersubpara, IList`1 level, IList`1 txt, IList`1 custom, IList`1 sZeros, String sNumbers, IList`1 sMinuses, String sOperators, IList`1 checkid, String flagNote, IList`1 VERSION, IList`1 prmTrack, IList`1 flag)
   at <xsl:template name="compiler:generated"> (112)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current, IList`1 newlevel, IList`1 checkid, IList`1 sZeros, String sNumbers, IList`1 sMinuses, String sOperators, IList`1 characterStyle, IList`1 verfoot, IList`1 level)
   at <xsl:template name="InsertFootnotes">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, IList`1 level, IList`1 verfoot, IList`1 characterStyle, String sOperators, IList`1 sMinuses, String sNumbers, IList`1 sZeros)
   at <xsl:template name="compiler:generated"> (31)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, XPathNavigator {urn:schemas-microsoft-com:xslt-debug}current, XPathNavigator quote, IList`1 charparahandlerStyle, IList`1 dpiPara, IList`1 imgOptionPara, IList`1 mastersubpara, IList`1 level, IList`1 txt, IList`1 custom, IList`1 sZeros, String sNumbers, IList`1 sMinuses, String sOperators, IList`1 checkid, String flagNote, IList`1 VERSION, IList`1 prmTrack, IList`1 flag)
   at <xsl:template name="Matter">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, IList`1 prmTrack, IList`1 version, IList`1 custom, IList`1 masterSub, String sOperators, XPathNavigator sMinuses, String sNumbers, XPathNavigator sZeros, IList`1 imgOption, IList`1 dpi, IList`1 charStyles, String matterType)
   at <xsl:template name="BodyMatter">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, IList`1 prmTrack, IList`1 version, IList`1 custom, IList`1 masterSub, String sOperators, XPathNavigator sMinuses, String sNumbers, XPathNavigator sZeros, IList`1 imgOption, IList`1 dpi, IList`1 charStyles)
   at <xsl:template name="compiler:generated"> (117)(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime, IList`1 doclang, IList`1 doclangbidi, IList`1 doclangeastAsia, IList`1 documentDate, IList`1 documentSubject, IList`1 documentDescription)
   at <xsl:template match="/">(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at Root(XmlQueryRuntime {urn:schemas-microsoft-com:xslt-debug}runtime)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
   at Daisy.SaveAsDAISY.Conversion.WordToDTBookXMLTransform.ConvertDocument(DocumentParameters document, ConversionParameters conversion, XmlDocument mergeTarget)
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Daisy.SaveAsDAISY.Conversion.DaisyClass.FootNoteId(Int32 i, Int32 level)
```

**Comment by NPavie** [comment]
I'm sorry you encountered this error.

Would it possible for you to send me the problematic file (or a sample that produces the same error) in a separate email at pavie.nicolas@gmail.com so that I could try to reproduce the issue ?

Thank you in advance,
